# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Strategic Roadmap to a Distinctive Kent State
email: your-email@domain.com
description: Plot your course on Kent State University’s Strategic Roadmap, animated by stories, data and images that highlight our journey to a distinctive Kent State.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://president.ideabasekent.com/prod/_site" # the base hostname & protocol for your site
twitter_username: kentstate
future: true
exclude: [node_modules,Gemfile,Gemfile.lock,Guardfile,gulpfile.js,assets/scss]

# Build settings
markdown: kramdown

# Collections
collections:
  priorities:
    output: true
    permalink: /priorities/:path/
  stories:
    output: true
    permalink: /stories/:path/
  videos:
    output: true
    permalink: /videos/:path/
  galleries:
    output: true
    permalink: /galleries/:path/
